### ISSUE TITLE
Merging a branch into master in Atlas didn't trigger a new release

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/bump2version-ci#15]
I'm not 100% sure the problem is caused by this action.

What happened: branch merged 5 hours ago:

<img width="1170" alt="image" src="https://github.com/Clinical-Genomics/bump2version-ci/assets/28093618/b5063aa7-9a89-4906-ba52-844e4ed56afa">

<hr>

Last release was 2 days ago:

<img width="273" alt="image" src="https://github.com/Clinical-Genomics/bump2version-ci/assets/28093618/d40fd6b6-fa27-4a7e-b99f-dae7aa2b99f4">

**Comment by northwestwitch** [comment]
AH yes, the error is caused by this action. See error log taken from the [failed job](https://github.com/Clinical-Genomics/atlas/actions/runs/8092720149/job/22113979006)

```
/usr/bin/docker run --name a943ac3ea0236dc39d41b18b51d8fc3005c25f_b934c4 --label a943ac --workdir /github/workspace --rm -e "BUMPVERSION_TOKEN" -e "BUMPVERSION_AUTHOR" -e "BUMPVERSION_EMAIL" -e "GITHUB_REPOSITORY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/atlas/atlas":"/github/workspace" a943ac:3ea0236dc39d41b18b51d8fc3005c25f
Cloning into 'atlas'...
fatal: tag '9.1[8](https://github.com/Clinical-Genomics/atlas/actions/runs/8092720149/job/22113979006#step:3:9).34' already exists
Traceback (most recent call last):
  File "/usr/local/bin/bump2version", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/bumpversion/cli.py", line 137, in main
    _tag_in_vcs(vcs, context, args)
  File "/usr/local/lib/python3.7/site-packages/bumpversion/cli.py", line 728, in _tag_in_vcs
    vcs.tag(sign_tags, tag_name, tag_message)
  File "/usr/local/lib/python3.7/site-packages/bumpversion/vcs.py", line 138, in tag
    subprocess.check_output(command)
  File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'tag', '[9](https://github.com/Clinical-Genomics/atlas/actions/runs/8092720149/job/22113979006#step:3:10).18.34', '--message', 'Bump version: 9.18.33 → 9.18.34']' returned non-zero exit status [12](https://github.com/Clinical-Genomics/atlas/actions/runs/8092720149/job/22113979006#step:3:13)8.
```

**Comment by northwestwitch** [comment]
Closing this as we have done the dirty fix in Atlas!
